apiVersion: v1
kind: Secret
metadata:
  name: postgresql-bucket-uri-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  POSTGRESQL_BUCKET_URI: {{ .Values.restore.bucket_uri | b64enc | quote }}
